
import { Language } from './types';

export const SUPPORTED_FORMATS = ['image/jpeg', 'image/png', 'image/webp', 'image/jpg', 'application/pdf'];

export const INITIAL_SETTINGS = {
  convertToPdf: true,
  saveSeparately: false,
  saveInGroup: false,
  useOCR: false,
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  'pt-BR': {
    selectAll: "Selecionar todos",
    clearAll: "Limpar todos",
    convertToPdf: "Converter para PDF",
    saveSeparately: "Salvar separado",
    saveInGroup: "Salvar em grupo",
    save: "Salvar",
    saving: "Salvando...",
    total: "Total",
    dragDrop: "Arraste ou adicione",
    dropHere: "Solte os arquivos",
    addFiles: "Adicionar arquivos",
    edit: "Editar",
    editorTitle: "Editor de Imagem",
    pdfEditorTitle: "Editor de PDF",
    undo: "Desfazer",
    redo: "Refazer",
    reset: "Restaurar",
    cancel: "Cancelar",
    confirm: "Confirmar Edição",
    removeBg: "Remover Fundo",
    removeBgBatch: "Remover Fundos (Sel.)",
    applyCrop: "Recortar Imagem",
    manualCrop: "Recorte Manual",
    cropInstructions: "Desenhe uma área para recortar. Arraste as bordas para ajustar.",
    processing: "Processando...",
    imageTools: "Ajustes de Imagem",
    language: "Português do Brasil",
    theme: "Tema",
    deleteDoc: "Excluir documento",
    search: "Visualizar",
    rotate: "Girar",
    page: "Página",
    savePdf: "Salvar PDF",
    loadingPdf: "Carregando PDF...",
    docSaved: "Documento(s) Salvo(s)",
    docSaveError: "Erro ao salvar documento(s)",
    openFolder: "Exibir pasta de destino",
    folderInfo: "Os arquivos foram salvos na sua pasta padrão de Downloads.",
    autoSort: "Ordenar Auto",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas com sucesso",
    sortError: "Erro ao ordenar páginas",
    zoomIn: "Aumentar Zoom",
    zoomOut: "Diminuir Zoom",
    zoomReset: "Restaurar Zoom",
    backToGrid: "Voltar para Grade",
    viewPage: "Visualizar Página",
    nextPage: "Próxima",
    prevPage: "Anterior",
    batchProcessError: "Erro ao processar algumas imagens.",
    rightsReserved: "Todos os direitos reservados",
    supportLink: "Clique Aqui para obter suporte",
    footerQuote: '"E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos" — Gálatas 6:9',
    brightness: "Brilho",
    contrast: "Contraste",
    adjustHelp: "Ajuste o contraste para facilitar a remoção do fundo.",
    applyAdjustments: "Aplicar Ajustes",
    updateAvailable: "Nova versão disponível",
    updateNow: "Atualizar",
    addPages: "Adicionar Páginas",
    splitPdf: "Dividir PDF",
    splitIntervals: "Intervalos de Página",
    splitPlaceholder: "Ex: 1-3, 5, 8-10",
    splitAction: "Dividir e Baixar",
    splitInvalid: "Intervalo inválido. Use formatos como 1-3 ou 5.",
    comingSoon: "Em breve: Compressão de PDF, recorte ajustável ao formato da imagem (perspectiva) e remoção de fundo por IA.",
    useOCR: "OCR (Texto Pesquisável)",
    ocrWarning: "O OCR torna o processo muito mais lento",
    ocrProcessing: "Reconhecendo texto (OCR)..."
  },
  'en': {
    selectAll: "Select All",
    clearAll: "Clear All",
    convertToPdf: "Convert to PDF",
    saveSeparately: "Save Separately",
    saveInGroup: "Save as Group",
    save: "Save",
    saving: "Saving...",
    total: "Total",
    dragDrop: "Drag or add",
    dropHere: "Drop files here",
    addFiles: "Add files",
    edit: "Edit",
    editorTitle: "Image Editor",
    pdfEditorTitle: "PDF Editor",
    undo: "Undo",
    redo: "Redo",
    reset: "Reset",
    cancel: "Cancel",
    confirm: "Confirm Edit",
    removeBg: "Remove Background",
    removeBgBatch: "Remove Bg (Sel.)",
    applyCrop: "Crop Image",
    manualCrop: "Manual Crop",
    cropInstructions: "Draw an area to crop. Drag edges to adjust.",
    processing: "Processing...",
    imageTools: "Image Tools",
    language: "English",
    theme: "Theme",
    deleteDoc: "Delete document",
    search: "Preview",
    rotate: "Rotate",
    page: "Page",
    savePdf: "Save PDF",
    loadingPdf: "Loading PDF...",
    docSaved: "Document(s) Saved",
    docSaveError: "Error saving document(s)",
    openFolder: "Show destination folder",
    folderInfo: "Files are saved to your default Downloads folder.",
    autoSort: "Auto Sort",
    sorting: "Sorting...",
    sortSuccess: "Pages sorted successfully",
    sortError: "Error sorting pages",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    zoomReset: "Reset Zoom",
    backToGrid: "Back to Grid",
    viewPage: "View Page",
    nextPage: "Next",
    prevPage: "Previous",
    batchProcessError: "Error processing some images.",
    rightsReserved: "All rights reserved",
    supportLink: "Click Here for support",
    footerQuote: '"And let us not grow weary of doing good, for in due season we will reap" — Galatians 6:9',
    brightness: "Brightness",
    contrast: "Contrast",
    adjustHelp: "Adjust contrast to help with background removal.",
    applyAdjustments: "Apply Adjustments",
    updateAvailable: "New version available",
    updateNow: "Update",
    addPages: "Add Pages",
    splitPdf: "Split PDF",
    splitIntervals: "Page Ranges",
    splitPlaceholder: "Ex: 1-3, 5, 8-10",
    splitAction: "Split and Download",
    splitInvalid: "Invalid range. Use formats like 1-3 or 5.",
    comingSoon: "Coming soon: PDF Compression, perspective-adjustable cropping, and AI background removal.",
    useOCR: "OCR (Searchable Text)",
    ocrWarning: "OCR makes the process much slower",
    ocrProcessing: "Recognizing text (OCR)..."
  },
  'es': {
    selectAll: "Seleccionar todos",
    clearAll: "Limpiar todo",
    convertToPdf: "Convertir a PDF",
    saveSeparately: "Guardar por separado",
    saveInGroup: "Guardar en grupo",
    save: "Guardar",
    saving: "Guardando...",
    total: "Total",
    dragDrop: "Arrastra o agrega",
    dropHere: "Suelta los archivos",
    addFiles: "Agregar archivos",
    edit: "Editar",
    editorTitle: "Editor de Imagen",
    pdfEditorTitle: "Editor de PDF",
    undo: "Deshacer",
    redo: "Rehacer",
    reset: "Restaurar",
    cancel: "Cancelar",
    confirm: "Confirmar Edición",
    removeBg: "Eliminar Fondo",
    removeBgBatch: "Eliminar Fondo (Sel.)",
    applyCrop: "Recortar Imagen",
    manualCrop: "Recorte Manual",
    cropInstructions: "Dibuja un área para recortar. Arrastra los bordes para ajustar.",
    processing: "Procesando...",
    imageTools: "Herramientas de Imagen",
    language: "Español",
    theme: "Tema",
    deleteDoc: "Eliminar documento",
    search: "Vista previa",
    rotate: "Girar",
    page: "Página",
    savePdf: "Guardar PDF",
    loadingPdf: "Cargando PDF...",
    docSaved: "Documento(s) Guardado(s)",
    docSaveError: "Error al guardar documento(s)",
    openFolder: "Mostrar carpeta de destino",
    folderInfo: "Los archivos se guardan en su carpeta de Descargas predeterminada.",
    autoSort: "Ordenando Auto",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas",
    sortError: "Error al ordenar",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    zoomReset: "Restablecer Zoom",
    backToGrid: "Volver a la cuadrícula",
    viewPage: "Ver Página",
    nextPage: "Siguiente",
    prevPage: "Anterior",
    batchProcessError: "Error al procesar algunas imágenes.",
    rightsReserved: "Todos los direitos reservados",
    supportLink: "Haga clic aquí para obtener soporte",
    footerQuote: '"No nos cansemos, pues, de hacer bien; porque a su tempo segaremos" — Gálatas 6:9',
    brightness: "Brillo",
    contrast: "Contraste",
    adjustHelp: "Ajuste el contraste para ayudar a eliminar el fondo.",
    applyAdjustments: "Aplicar Ajustes",
    updateAvailable: "Nueva versión disponible",
    updateNow: "Update",
    addPages: "Añadir páginas",
    splitPdf: "Dividir PDF",
    splitIntervals: "Intervalos de Página",
    splitPlaceholder: "Ej: 1-3, 5, 8-10",
    splitAction: "Dividir y Descargar",
    splitInvalid: "Intervalo inválido. Use formatos como 1-3 o 5.",
    comingSoon: "Próximamente: Compresión de PDF, recorte ajustable al formato de imagen (perspectiva) y eliminación de fondo por IA.",
    useOCR: "OCR (Texto buscable)",
    ocrWarning: "El OCR hace que el proceso sea mucho más lento",
    ocrProcessing: "Reconociendo texto (OCR)..."
  },
  'he': {
    selectAll: "בחר הכל",
    clearAll: "נקה הכל",
    convertToPdf: "המר ל-PDF",
    saveSeparately: "שמור בנפרד",
    saveInGroup: "שמור כקבוצה",
    save: "שמור",
    saving: "שומר...",
    total: "סה\"כ",
    dragDrop: "גרור או הוסף",
    dropHere: "שחרר קבצים כאן",
    addFiles: "הוסף קבצים",
    edit: "ערוך",
    editorTitle: "עורך תמונות",
    pdfEditorTitle: "עורך PDF",
    undo: "בטל",
    redo: "בצע שוב",
    reset: "אפס",
    cancel: "ביטול",
    confirm: "אשר עריכה",
    removeBg: "הסר רקע",
    removeBgBatch: "הסר רקע (נבחרים)",
    applyCrop: "גזור תמונה",
    manualCrop: "גזירה ידנית",
    cropInstructions: "צייר אזור לגזירה. גרור קצוות להתאמה.",
    processing: "מעבד...",
    imageTools: "כלי תמונה",
    language: "עברית",
    theme: "ערכת נושא",
    deleteDoc: "מחק מסמך",
    search: "תצוגה מקדימה",
    rotate: "סובב",
    page: "עמוד",
    savePdf: "שמור PDF",
    loadingPdf: "טוען PDF...",
    docSaved: "המסמך נשמר",
    docSaveError: "שגיאה בשמירת המסמך",
    openFolder: "הצג תיקיית יעד",
    folderInfo: "הקבצים נשמרים בתיקיית ההורדות שלך.",
    autoSort: "מיון אוטומטי",
    sorting: "ממיין...",
    sortSuccess: "העמודים מוינו בהצלחה",
    sortError: "שגיאה במיון העמודים",
    zoomIn: "הגדל",
    zoomOut: "הקטן",
    zoomReset: "אפס זום",
    backToGrid: "חזור לרשת",
    viewPage: "צפה בעמוד",
    nextPage: "הבא",
    prevPage: "הקודם",
    batchProcessError: "שגיאה בעיבוד חלק מהתמונות.",
    rightsReserved: "כל הזכויות שמורות",
    supportLink: "לחץ כאן לתמיכה",
    footerQuote: '"ואל־ייעף לבנו מעשות טוב כי בעתו נקצר אם לא נרפה" — הגלטים ו:ט',
    brightness: "בהירות",
    contrast: "ניגודיות",
    adjustHelp: "כוונן ניגודיות כדי לעזור בהסרת רקע.",
    applyAdjustments: "החל התאמות",
    updateAvailable: "גרסה חדשה זמינה",
    updateNow: "עדכן",
    addPages: "הוסף עמודים",
    splitPdf: "פצל PDF",
    splitIntervals: "טווחי עמודים",
    splitPlaceholder: "למשל: 1-3, 5, 8-10",
    splitAction: "פצל והורד",
    splitInvalid: "טווח לא תקין. השתמש בפורמט כמו 1-3 או 5.",
    comingSoon: "Coming soon: PDF Compression, perspective-adjustable cropping, and AI background removal.",
    useOCR: "OCR (טקסט ניתן לחיפוש)",
    ocrWarning: "OCR הופך את התהליך לאיטי יותר",
    ocrProcessing: "מזהה טקסט (OCR)..."
  },
  'el': {
    selectAll: "Επιλογή όλων",
    clearAll: "Εκκαθάριση όλων",
    convertToPdf: "Μετατροπή σε PDF",
    saveSeparately: "Αποθήκευση ξεχωριστά",
    saveInGroup: "Αποθήκευση ως ομάδα",
    save: "Αποθήκευση",
    saving: "Αποθήκευση...",
    total: "Σύνολο",
    dragDrop: "Σύρετε ή προσθέστε",
    dropHere: "Αφήστε τα αρχεία εδώ",
    addFiles: "Προσθήκη αρχείων",
    edit: "Επεξεργασία",
    editorTitle: "Επεξεργαστής Εικόνας",
    pdfEditorTitle: "Επεξεργαστής PDF",
    undo: "Αναίρεση",
    redo: "Επανάληψη",
    reset: "Επαναφορά",
    cancel: "Ακύρωση",
    confirm: "Επιβεβαίωση",
    removeBg: "Αφαίρεση φόντου",
    removeBgBatch: "Αφαίρεση φόντου (Επιλ.)",
    applyCrop: "Περικοπή",
    manualCrop: "Χειροκίνητη περικοπή",
    cropInstructions: "Σχεδιάστε μια περιοχή για περικοπή. Σύρετε τις άκρες για προσαρμογή.",
    processing: "Επεξεργασία...",
    imageTools: "Εργαλεία Εικόνας",
    language: "Ελληνικά",
    theme: "Θέμα",
    deleteDoc: "Διαγραφή εγγράφου",
    search: "Προεπισκόπηση",
    rotate: "Περιστροφή",
    page: "Σελίδα",
    savePdf: "Αποθήκευση PDF",
    loadingPdf: "Φόρτωση PDF...",
    docSaved: "Το έγγραφο αποθηκεύτηκε",
    docSaveError: "Σφάλμα κατά την αποθήκευση",
    openFolder: "Εμφάνιση φακέλου",
    folderInfo: "Τα αρχεία αποθηκεύονται στον φάκελο Λήψεις.",
    autoSort: "Αυτόματη ταξινόμηση",
    sorting: "Ταξινόμηση...",
    sortSuccess: "Οι σελίδες ταξινομήθηκαν",
    sortError: "Σφάλμα ταξινόμησης",
    zoomIn: "Μεγέθυνση",
    zoomOut: "Σμίκρυνση",
    zoomReset: "Επαναφορά ζουμ",
    backToGrid: "Επιστροφή στο πλέγμα",
    viewPage: "Προβολή σελίδας",
    nextPage: "Επόμενη",
    prevPage: "Προηγούμενη",
    batchProcessError: "Σφάλμα επεξεργασίας εικόνων.",
    rightsReserved: "Όλα τα δικαιώματα διατηρούνται",
    supportLink: "Κάντε κλικ εδώ για υποστήριξη",
    footerQuote: '"το δε καλόν ποιούντες μη εγκακώμεν, καιρώ γαρ ιδίω θερίσομεν μη εκλυόμενοι" — Προς Γαλάτας 6:9',
    brightness: "Φωτεινότητα",
    contrast: "Αντίθεση",
    adjustHelp: "Προσαρμόστε την αντίθεση para ευκολότερη αφαίρεση φόντου.",
    applyAdjustments: "Εφαρμογή προσαρμογών",
    updateAvailable: "Νέα έκδοση διαθέσιμη",
    updateNow: "Ενημέρωση",
    addPages: "Προσθήκη σελίδων",
    splitPdf: "Διαχωρισμός PDF",
    splitIntervals: "Εύρος σελίδων",
    splitPlaceholder: "Π.χ.: 1-3, 5, 8-10",
    splitAction: "Διαχωρισμός και λήψη",
    splitInvalid: "Μη έγκυρο εύρος.",
    comingSoon: "Coming soon: PDF Compression, perspective-adjustable cropping, and AI background removal.",
    useOCR: "OCR (Αναζητήσιμο κείμενο)",
    ocrWarning: "Το OCR καθυστερεί τη διαδικασία",
    ocrProcessing: "Αναγνώριση κειμένου (OCR)..."
  }
};
