
import { Language } from './types';

export const SUPPORTED_FORMATS = ['image/jpeg', 'image/png', 'image/webp', 'image/jpg', 'application/pdf'];

export const INITIAL_SETTINGS = {
  convertToPdf: true,
  saveSeparately: false,
  saveInGroup: false,
  useOCR: false,
};

// Added missing translations for 'es', 'el', and 'he' to fulfill the Language type requirement.
// Added eUndo, eRedo, and eReset to all languages for consistency with pt-BR.
export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  'pt-BR': {
    selectAll: "Selecionar todos",
    clearAll: "Limpar todos",
    convertToPdf: "Converter para PDF",
    saveSeparately: "Salvar separado",
    saveInGroup: "Salvar em grupo",
    save: "Salvar",
    saving: "Salvando...",
    total: "Total",
    dragDrop: "Arraste ou adicione",
    dropHere: "Solte os arquivos",
    addFiles: "Adicionar arquivos",
    edit: "Editar",
    editorTitle: "Editor de Imagem",
    pdfEditorTitle: "Editor de PDF",
    undo: "Desfazer",
    redo: "Refazer",
    reset: "Restaurar Original",
    restore: "Restaurar Lote",
    cancel: "Cancelar",
    confirm: "Confirmar Edição",
    removeBg: "Remover Fundo",
    autoCropBatch: "Recorte Automático (Sel.)",
    applyCrop: "Recortar Imagem",
    manualCrop: "Recorte Manual",
    cropInstructions: "Desenhe uma área para recortar. Arraste as bordas para ajustar.",
    processing: "Processando...",
    imageTools: "Ajustes de Imagem",
    language: "Português do Brasil",
    theme: "Tema",
    deleteDoc: "Excluir documento",
    search: "Visualizar",
    rotate: "Girar",
    page: "Página",
    savePdf: "Salvar PDF",
    loadingPdf: "Carregando PDF...",
    docSaved: "Documento(s) Salvo(s)",
    docSaveError: "Erro ao salvar documento(s)",
    openFolder: "Exibir pasta de destino",
    folderInfo: "Os arquivos foram salvos na sua pasta padrão de Downloads.",
    autoSort: "Ordenar Auto",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas com sucesso",
    sortError: "Erro ao ordenar páginas",
    zoomIn: "Aumentar Zoom",
    zoomOut: "Diminuir Zoom",
    zoomReset: "Restaurar Zoom",
    eUndo: "Desfazer",
    eRedo: "Refazer",
    eReset: "Reset",
    backToGrid: "Voltar para Grade",
    viewPage: "Visualizar Página",
    nextPage: "Próxima",
    prevPage: "Anterior",
    batchProcessError: "Erro ao processar algumas imagens.",
    rightsReserved: "Todos os direitos reservados",
    supportLink: "Clique Aqui para obter suporte",
    footerQuote: '"E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos" — Gálatas 6:9',
    brightness: "Brilho",
    contrast: "Contraste",
    adjustHelp: "Ajuste o contraste para facilitar a remoção do fundo.",
    applyAdjustments: "Aplicar Ajustes",
    updateAvailable: "Nova versão disponível",
    updateNow: "Atualizar",
    addPages: "Adicionar Páginas",
    splitPdf: "Dividir PDF",
    splitIntervals: "Intervalos de Página",
    splitPlaceholder: "Ex: 1-3, 5, 8-10",
    splitAction: "Dividir e Baixar",
    splitInvalid: "Intervalo inválido. Use formatos como 1-3 ou 5.",
    comingSoon: "Em breve: Compressão de PDF.",
    useOCR: "OCR (Texto Pesquisável)",
    ocrWarning: "O OCR torna o processo muito mais lento",
    ocrProcessing: "Reconhecendo texto (OCR)...",
    about: "Sobre",
    aboutTitle: "Sobre Αρχή PDF",
    developedBy: "Criado e desenvolvido por",
    openSourceLicenses: "Licenças Open Source",
    version: "Versão"
  },
  'en': {
    selectAll: "Select All",
    clearAll: "Clear All",
    convertToPdf: "Convert to PDF",
    saveSeparately: "Save Separately",
    saveInGroup: "Save as Group",
    save: "Save",
    saving: "Saving...",
    total: "Total",
    dragDrop: "Drag or add",
    dropHere: "Drop files here",
    addFiles: "Add files",
    edit: "Edit",
    editorTitle: "Image Editor",
    pdfEditorTitle: "PDF Editor",
    undo: "Undo",
    redo: "Redo",
    reset: "Reset to Original",
    restore: "Restore Batch",
    cancel: "Cancel",
    confirm: "Confirm Edit",
    removeBg: "Remove Background",
    autoCropBatch: "Auto Crop (Sel.)",
    applyCrop: "Crop Image",
    manualCrop: "Manual Crop",
    cropInstructions: "Draw an area to crop. Drag edges to adjust.",
    processing: "Processing...",
    imageTools: "Image Tools",
    language: "English",
    theme: "Theme",
    deleteDoc: "Delete document",
    search: "Preview",
    rotate: "Rotate",
    page: "Page",
    savePdf: "Save PDF",
    loadingPdf: "Loading PDF...",
    docSaved: "Document(s) Saved",
    docSaveError: "Error saving document(s)",
    openFolder: "Show destination folder",
    folderInfo: "Files are saved to your default Downloads folder.",
    autoSort: "Auto Sort",
    sorting: "Sorting...",
    sortSuccess: "Pages sorted successfully",
    sortError: "Error sorting pages",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    zoomReset: "Reset Zoom",
    eUndo: "Undo",
    eRedo: "Redo",
    eReset: "Reset",
    backToGrid: "Back to Grid",
    viewPage: "View Page",
    nextPage: "Next",
    prevPage: "Previous",
    batchProcessError: "Error processing some images.",
    rightsReserved: "All rights reserved",
    supportLink: "Click Here for support",
    footerQuote: '"And let us not grow weary of doing good, for in due season we will reap" — Galatians 6:9',
    brightness: "Brightness",
    contrast: "Contrast",
    adjustHelp: "Adjust contrast to help with background removal.",
    applyAdjustments: "Apply Adjustments",
    updateAvailable: "New version available",
    updateNow: "Update",
    addPages: "Add Pages",
    splitPdf: "Split PDF",
    splitIntervals: "Page Ranges",
    splitPlaceholder: "Ex: 1-3, 5, 8-10",
    splitAction: "Split and Download",
    splitInvalid: "Invalid range. Use formats like 1-3 or 5.",
    comingSoon: "Coming soon: PDF Compression.",
    useOCR: "OCR (Searchable Text)",
    ocrWarning: "OCR makes the process much slower",
    ocrProcessing: "Recognizing text (OCR)...",
    about: "About",
    aboutTitle: "About Αρχή PDF",
    developedBy: "Created and developed by",
    openSourceLicenses: "Open Source Licenses",
    version: "Version"
  },
  'es': {
    selectAll: "Seleccionar todo",
    clearAll: "Limpiar todo",
    convertToPdf: "Convertir a PDF",
    saveSeparately: "Guardar por separado",
    saveInGroup: "Guardar como grupo",
    save: "Guardar",
    saving: "Guardando...",
    total: "Total",
    dragDrop: "Arrastre o añada",
    dropHere: "Suelte los archivos aquí",
    addFiles: "Añadir archivos",
    edit: "Editar",
    editorTitle: "Editor de imágenes",
    pdfEditorTitle: "Editor de PDF",
    undo: "Deshacer",
    redo: "Rehacer",
    reset: "Restablecer original",
    restore: "Restaurar lote",
    cancel: "Cancelar",
    confirm: "Confirmar edición",
    removeBg: "Eliminar fondo",
    autoCropBatch: "Recorte automático (Sel.)",
    applyCrop: "Recortar imagen",
    manualCrop: "Recorte manual",
    cropInstructions: "Dibuje un área para recortar. Arrastre los bordes para ajustar.",
    processing: "Procesando...",
    imageTools: "Herramientas de imagen",
    language: "Español",
    theme: "Tema",
    deleteDoc: "Eliminar documento",
    search: "Vista previa",
    rotate: "Girar",
    page: "Página",
    savePdf: "Guardar PDF",
    loadingPdf: "Cargando PDF...",
    docSaved: "Documento(s) guardado(s)",
    docSaveError: "Error al guardar documento(s)",
    openFolder: "Mostrar carpeta de destino",
    folderInfo: "Los archivos se guardan en su carpeta de descargas predeterminada.",
    autoSort: "Orden automático",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas con éxito",
    sortError: "Error al ordenar páginas",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    zoomReset: "Restablecer zoom",
    eUndo: "Deshacer",
    eRedo: "Rehacer",
    eReset: "Reiniciar",
    backToGrid: "Volver a la cuadrícula",
    viewPage: "Ver página",
    nextPage: "Siguiente",
    prevPage: "Anterior",
    batchProcessError: "Error al procesar algunas imágenes.",
    rightsReserved: "Todos los derechos reservados",
    supportLink: "Haga clic aquí para obtener ayuda",
    footerQuote: '"Y no nos cansemos de hacer el bien, pues a su tiempo segaremos" — Gálatas 6:9',
    brightness: "Brillo",
    contrast: "Contraste",
    adjustHelp: "Ajuste el contraste para ayudar a eliminar el fondo.",
    applyAdjustments: "Aplicar ajustes",
    updateAvailable: "Nueva versión disponible",
    updateNow: "Actualizar",
    addPages: "Añadir páginas",
    splitPdf: "Dividir PDF",
    splitIntervals: "Rangos de página",
    splitPlaceholder: "Ej: 1-3, 5, 8-10",
    splitAction: "Dividir y descargar",
    splitInvalid: "Rango inválido. Use formatos como 1-3 o 5.",
    comingSoon: "Próximamente: Compresión de PDF.",
    useOCR: "OCR (Texto buscable)",
    ocrWarning: "El OCR hace que el proceso sea mucho más lento",
    ocrProcessing: "Reconocimiento de texto (OCR)...",
    about: "Acerca de",
    aboutTitle: "Acerca de Αρχή PDF",
    developedBy: "Creado y desarrollado por",
    openSourceLicenses: "Licencias de código abierto",
    version: "Versión"
  },
  'el': {
    selectAll: "Επιλογή όλων",
    clearAll: "Καθαρισμός όλων",
    convertToPdf: "Μετατροπή σε PDF",
    saveSeparately: "Αποθήκευση ξεχωριστά",
    saveInGroup: "Αποθήκευση ως ομάδα",
    save: "Αποθήκευση",
    saving: "Αποθήκευση...",
    total: "Σύνολο",
    dragDrop: "Σύρετε ή προσθέστε",
    dropHere: "Αφήστε τα αρχεία εδώ",
    addFiles: "Προσθήκη αρχείων",
    edit: "Επεξεργασία",
    editorTitle: "Επεξεργαστής εικόνας",
    pdfEditorTitle: "Επεξεργαστής PDF",
    undo: "Αναίρεση",
    redo: "Επαναφορά",
    reset: "Επαναφορά στο αρχικό",
    restore: "Επαναφορά παρτίδας",
    cancel: "Ακύρωση",
    confirm: "Επιβεβαίωση επεξεργασίας",
    removeBg: "Αφαίρεση φόντου",
    autoCropBatch: "Αυτόματη περικοπή (Επιλ.)",
    applyCrop: "Περικοπή εικόνας",
    manualCrop: "Χειροκίνητη περικοπή",
    cropInstructions: "Σχεδιάστε μια περιοχή για περικοπή. Σύρετε τις άκρες για προσαρμογή.",
    processing: "Επεξεργασία...",
    imageTools: "Εργαλεία εικόνας",
    language: "Ελληνικά",
    theme: "Θέμα",
    deleteDoc: "Διαγραφή εγγράφου",
    search: "Προεπισκόπηση",
    rotate: "Περιστροφή",
    page: "Σελίδα",
    savePdf: "Αποθήκευση PDF",
    loadingPdf: "Φόρτωση PDF...",
    docSaved: "Τα έγγραφα αποθηκεύτηκαν",
    docSaveError: "Σφάλμα κατά την αποθήκευση εγγράφων",
    openFolder: "Εμφάνιση φακέλου προορισμού",
    folderInfo: "Τα αρχεία αποθηκεύονται στον προεπιλεγμένο φάκελο λήψεων.",
    autoSort: "Αυτόματη ταξινόμηση",
    sorting: "Ταξινόμηση...",
    sortSuccess: "Οι σελίδες ταξινομήθηκαν με επιτυχία",
    sortError: "Σφάλμα κατά την ταξινόμηση σελίδων",
    zoomIn: "Μεγέθυνση",
    zoomOut: "Σμίκρυνση",
    zoomReset: "Επαναφορά ζουμ",
    eUndo: "Αναίρεση",
    eRedo: "Επαναφορά",
    eReset: "Επαναφορά",
    backToGrid: "Επιστροφή στο πλέγμα",
    viewPage: "Προβολή σελίδας",
    nextPage: "Επόμενο",
    prevPage: "Προηγούμενο",
    batchProcessError: "Σφάλμα κατά την επεξεργασία ορισμένων εικόνων.",
    rightsReserved: "Με επιφύλαξη παντός δικαιώματος",
    supportLink: "Κάντε κλικ εδώ για υποστήριξη",
    footerQuote: '"Και ας μην αποκάμουμε κάνοντας το καλό, γιατί στον δικό του καιρό θα θερίσουμε" — Γαλάτας 6:9',
    brightness: "Φωτεινότητα",
    contrast: "Αντίθεση",
    adjustHelp: "Προσαρμόστε την αντίθεση για να βοηθήσετε στην αφαίρεση του φόντου.",
    applyAdjustments: "Εφαρμογή προσαρμογών",
    updateAvailable: "Νέα έκδοση διαθέσιμη",
    updateNow: "Ενημέρωση",
    addPages: "Προσθήκη σελίδων",
    splitPdf: "Διαίρεση PDF",
    splitIntervals: "Εύρος σελίδων",
    splitPlaceholder: "Πχ: 1-3, 5, 8-10",
    splitAction: "Διαίρεση και λήψη",
    splitInvalid: "Μη έγκυρο εύρος. Χρησιμοποιήστε μορφές όπως 1-3 ή 5.",
    comingSoon: "Σύντομα κοντά σας: Συμπίεση PDF.",
    useOCR: "OCR (Αναζητήσιμο κείμενο)",
    ocrWarning: "Το OCR καθυστερεί σημαντικά τη διαδικασία",
    ocrProcessing: "Αναγνώριση κειμένου (OCR)...",
    about: "Σχετικά",
    aboutTitle: "Σχετικά με το Αρχή PDF",
    developedBy: "Δημιουργήθηκε από τους",
    openSourceLicenses: "Άδειες ανοιχτού κώδικα",
    version: "Έκδοση"
  },
  'he': {
    selectAll: "בחר הכל",
    clearAll: "נקה הכל",
    convertToPdf: "המר ל-PDF",
    saveSeparately: "שמור בנפרד",
    saveInGroup: "שמור כקבוצה",
    save: "שמור",
    saving: "שומר...",
    total: "סה\"כ",
    dragDrop: "גרור או הוסף",
    dropHere: "שחרר קבצים כאן",
    addFiles: "הוסף קבצים",
    edit: "ערוך",
    editorTitle: "עורך תמונות",
    pdfEditorTitle: "עורך PDF",
    undo: "בטל",
    redo: "בצע שוב",
    reset: "אפס למקור",
    restore: "שחזר אצווה",
    cancel: "ביטול",
    confirm: "אשר עריכה",
    removeBg: "הסר רקע",
    autoCropBatch: "חיתוך אוטומטי (נבחרים)",
    applyCrop: "חתוך תמונה",
    manualCrop: "חיתוך ידני",
    cropInstructions: "צייר אזור לחיתוך. גרור קצוות להתאמה.",
    processing: "מעבד...",
    imageTools: "כלי תמונה",
    language: "עברית",
    theme: "ערכת נושא",
    deleteDoc: "מחק מסמך",
    search: "תצוגה מקדימה",
    rotate: "סובב",
    page: "עמוד",
    savePdf: "שמור PDF",
    loadingPdf: "טוען PDF...",
    docSaved: "המסמך/ים נשמרו",
    docSaveError: "שגיאה בשמירת המסמך/ים",
    openFolder: "הצג תיקיית יעד",
    folderInfo: "הקבצים נשמרים בתיקיית ההורדות המוגדרת כברירת מחדל.",
    autoSort: "מיון אוטומטי",
    sorting: "ממיין...",
    sortSuccess: "העמודים מוינו בהצלחה",
    sortError: "שגיאה במיון העמודים",
    zoomIn: "התקרב",
    zoomOut: "התרחק",
    zoomReset: "אפס זום",
    eUndo: "בטל",
    eRedo: "בצע שוב",
    eReset: "אפס",
    backToGrid: "חזור לרשת",
    viewPage: "צפה בעמוד",
    nextPage: "הבא",
    prevPage: "הקודם",
    batchProcessError: "שגיאה בעיבוד חלק מהתמונות.",
    rightsReserved: "כל הזכויות שמורות",
    supportLink: "לחץ כאן לתמיכה",
    footerQuote: "\"ואל נלאה מעשות הטוב, כי בעתו נקצר אם לא נרפה\" — גלטיים ו:ט",
    brightness: "בהירות",
    contrast: "ניגודיות",
    adjustHelp: "כוון ניגודיות כדי לסייע בהסרת הרקע.",
    applyAdjustments: "החל התאמות",
    updateAvailable: "גרסה חדשה זמינה",
    updateNow: "עדכן",
    addPages: "הוסף עמודים",
    splitPdf: "פצל PDF",
    splitIntervals: "טווחי עמודים",
    splitPlaceholder: "למשל: 1-3, 5, 8-10",
    splitAction: "פצל והורד",
    splitInvalid: "טווח לא תקין. השתמש בפורמטים כמו 1-3 או 5.",
    comingSoon: "בבקרוב: דחיסת קבצי PDF.",
    useOCR: "OCR (טקסט שניתן לחיפוש)",
    ocrWarning: "OCR הופך את התהליך לאיטי משמעותית",
    ocrProcessing: "מזהה טקסט (OCR)...",
    about: "אודות",
    aboutTitle: "אודות Αρχή PDF",
    developedBy: "נוצר ופותח על ידי",
    openSourceLicenses: "רישיונות קוד פתוח",
    version: "גרסה"
  }
};
